CREATE TABLE `Role` ( `Id` integer PRIMARY KEY,`Name` varchar(16),`Description` varchar(128));
CREATE TABLE `Users_public` (`Id` integer PRIMARY KEY,`Person_Id` integer,`Username` varchar(32),`Profile_Picture` varchar(128),`Created_At` DateTime, `Updated_At` DateTime,`Deleted_At` DateTime);
CREATE TABLE `Users_private` ( `Id` integer PRIMARY KEY, `Role_Id` integer, `Email` varchar(64), `Password` varchar(64), `Token` varchar(64));
CREATE TABLE `Following` ( `User_Id_Followed` integer, `User_Id_Follower` integer, `Followed_At` DateTime );
CREATE TABLE `Video` ( `Id` integer PRIMARY KEY, `User_Id` integer, `File_Id` integer, `Title` varchar(32), `Description` varchar(128), `Url` varchar(64), `Created_At` DateTime, `Updated_At` DateTime, `Deleted_At` DateTime );
CREATE TABLE `Reaction` ( `User_Id` integer, `Video_Id` integer, `Created_At` DateTime, `Updated_At` DateTime );
CREATE TABLE `File` ( `Id` integer PRIMARY KEY, `File_Name` varchar(32), `File_location` varchar(128), `Created_At` DateTime, `Deleted_At` DateTime );
ALTER TABLE `Reaction` ADD FOREIGN KEY (`Video_Id`) REFERENCES `Video` (`Id`);
ALTER TABLE `Video` ADD FOREIGN KEY (`File_Id`) REFERENCES `File` (`Id`);
ALTER TABLE `Reaction` ADD FOREIGN KEY (`User_Id`) REFERENCES `Users_public` (`Id`);
ALTER TABLE `Following` ADD FOREIGN KEY (`User_Id_Followed`) REFERENCES `Users_public` (`Id`);
ALTER TABLE `Following` ADD FOREIGN KEY (`User_Id_Follower`) REFERENCES `Users_public` (`Id`);
ALTER TABLE `Video` ADD FOREIGN KEY (`User_Id`) REFERENCES `Users_public` (`Id`);
ALTER TABLE `Users_public` ADD FOREIGN KEY (`Person_Id`) REFERENCES `Users_private` (`Id`);
ALTER TABLE `Users_private` ADD FOREIGN KEY (`Role_Id`) REFERENCES `Role` (`Id`);